### ISSUE TITLE
Is there have a bug?

### ISSUE THREAD

**Issue by sucof** [programa-stic/Marvin-static-Analyzer#1]
~/Marvin-static-Analyzer# python MarvinStaticAnalyzer.py /root/test/
===================================APKS===================================
/root/test/InsecureBankv2.apk
===================================APKS===================================
cd SAAF-MODULE; java -jar SAAF.jar -nq -nodb -hl "/root/test/InsecureBankv2.apk"
Feb 23, 2016 11:04:09 AM brut.androlib.ApkDecoder decode
INFO: Using Apktool 2.0.0-RC2 on InsecureBankv2.apk
Feb 23, 2016 11:04:10 AM brut.androlib.res.AndrolibResources loadMainPkg
INFO: Loading resource table...
Feb 23, 2016 11:04:11 AM brut.androlib.res.AndrolibResources loadMainPkg
INFO: Loading resource table...
Feb 23, 2016 11:04:11 AM brut.androlib.Androlib decodeResourcesRaw
INFO: Copying raw resources...
Feb 23, 2016 11:04:12 AM brut.androlib.Androlib decodeSourcesSmali
INFO: Baksmaling classes.dex...
Feb 23, 2016 11:04:27 AM brut.androlib.Androlib decodeRawFiles
INFO: Copying assets and libs...
Feb 23, 2016 11:04:27 AM brut.androlib.Androlib decodeUnknownFiles
INFO: Copying unknown files...
Feb 23, 2016 11:04:28 AM brut.androlib.Androlib writeOriginalFiles
INFO: Copying original files...
Feb 23, 2016 11:04:29 AM brut.androlib.res.AndrolibResources loadMainPkg
INFO: Loading resource table...
Feb 23, 2016 11:04:30 AM brut.androlib.res.AndrolibResources decodeManifest
INFO: Decoding AndroidManifest.xml with only framework resources...
Feb 23, 2016 11:04:32 AM brut.androlib.res.AndrolibResources loadFrameworkPkg
INFO: Loading resource table from file: /root/apktool/framework/1.apk
Cleaning up unclosed ZipFile for archive /root/apktool/framework/1.apk
Cleaning up unclosed ZipFile for archive /root/test/InsecureBankv2.apk
Cleaning up unclosed ZipFile for archive /root/test/InsecureBankv2.apk
Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x000000075c2bd000, 315088896, 0) failed; error='Cannot allocate memory' (errno=12)
There was an error with the analysis
Traceback (most recent call last):
  File "MarvinStaticAnalyzer.py", line 99, in worker
    analyze_vulnerabilities_from(filename)
  File "MarvinStaticAnalyzer.py", line 47, in analyze_vulnerabilities_from
    return analyze_vulnerabilities(apk_file,_apk,vm,dx)
  File "MarvinStaticAnalyzer.py", line 89, in analyze_vulnerabilities
    final_report.update(SAAFModuleAnalyzer(apk_file).get_clean_report())
  File "/root/Marvin-static-Analyzer/SAAFAnalyzer.py", line 61, in get_clean_report
    report = self.open_xml_report()
  File "/root/Marvin-static-Analyzer/SAAFAnalyzer.py", line 55, in open_xml_report
    xml = max(glob.glob('SAAF-MODULE/reports/Report-' + self.file + '*'), key=os.path.getctime)
ValueError: max() arg is an empty sequence

It is not work to analysis the app named InsecureBankv2.apk, my os is ubuntu 14.04.

**Comment by xeroxnir** [comment]
Hi, 

I'm just guessing but perhaps you ran out of memory for running SAAF and that finished the SAAF analysis early and no report was generated. Did you check if a report in that path was generated properly?

Joaquín

**Comment by ia-sadosky** [comment]
hm still there is no error checking, this is a bug nonetheless

**Comment by sucof** [comment]
no, there is no report.

**Comment by jheguia** [comment]
It says Java ran out of memory. How much RAM do you have where you run the program?

**Comment by sucof** [comment]
2G RAM in a VM.

**Comment by jheguia** [comment]
That's it then. I suggest at least 4GB.
